services:
  - type: web
    name: new-fb-project
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SELENIUM_HEADLESS
        value: "True"
      - key: DEBUG
        value: "False"
      - key: MONGO_URI
        sync: false  # Set this in Render dashboard (secret)
      - key: MONGO_DB_NAME
        value: "facebook_pages"
